version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1
    command: python manage.py runserver 0.0.0.0:8000

  redis:
    image: redis
    ports:
      - "6379:6379"
